# ----------------------------------------------
# PRODUCTION
# ----------------------------------------------
ARG NODE_VERSION=18.13.0

FROM node:${NODE_VERSION}-slim

RUN apt-get clean && apt-get -qq update && apt-get -qq upgrade -y

# Setup correct timezone for docker instance
ENV TZ=Europe/Copenhagen
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Set workding directory
WORKDIR /app